version: '3.8'

services:
  vuln-web:
    build: ./vuln-web
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - app.env
    environment:
      - PYTHONPATH=/app

  db:
    image: postgres:13
    # Remove the ports section to prevent exposing the database to the host machine
    env_file:
      - db.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# Define a custom network (optional but recommended for clarity)
networks:
  default:
    driver: bridge
