-- init.sql
\c vuln_web

CREATE TABLE impenetrable_07062024_feedbacks (
    impenetrable_07062024_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CYCLE) PRIMARY KEY,
    impenetrable_07062024_message VARCHAR(2048) NOT NULL
);

CREATE TABLE impenetrable_07062024_users (
    impenetrable_07062024_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CYCLE) PRIMARY KEY,
    impenetrable_07062024_bio VARCHAR(255) NOT NULL
);


-- FLAG IN THE BIO FIELD
INSERT INTO impenetrable_07062024_users (impenetrable_07062024_bio) VALUES (substring(md5(random()::text), 1, 20));

CREATE USER vuln_web WITH PASSWORD '37893c2e099b2da1c60a56d3f175356428c5059d';

-- Grant CRUD permissions on feedback table to vuln_web
GRANT SELECT, INSERT, UPDATE, DELETE ON impenetrable_07062024_feedbacks TO vuln_web;


-- Grant add-only (SELECT) permission on feedback table to vuln_web
GRANT SELECT ON impenetrable_07062024_users TO vuln_web;