# Use an official Python runtime as a parent image
FROM martinthinhnguyen/observer-python-runtime:latest

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app

COPY . /app/

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt


# Define environment variables
ENV QUART_APP=app:app

# Run quart when the container launches
CMD ["python", "server.py"]
